### ISSUE TITLE
UnicodeDecodeError with accentued username

### ISSUE THREAD

**Issue by hista** [IvanMalison/okcupyd#47]
There is an issue with accentued usernames:

/usr/local/lib/python2.7/dist-packages/okcupyd/session.py:68: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if log_in_name.lower() != username.lower():
Traceback (most recent call last):
  File "/usr/local/bin/okcupyd", line 9, in <module>
    load_entry_point('okcupyd==0.9.0', 'console_scripts', 'okcupyd')()
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/__init__.py", line 32, in interactive
    u = User()
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/user.py", line 53, in __init__
    self._session = session or Session.login()
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/session.py", line 45, in login
    session.do_login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/okcupyd/session.py", line 70, in do_login
    u'got {1}'.format(username, log_in_name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)

**Comment by IvanMalison** [comment]
Sorry for the delay @hista. I'm taking a look at this now.

**Comment by hista** [comment]
Hi Ivan,

Is this issue solved now?

Best regards

**Comment by IvanMalison** [comment]
I think I did fix it but I haven't pushed it yet. Testing is sort of a pain for me right now because my ip address was blocked. Let me take a look.

**Comment by hista** [comment]
Hi Ivan,

Few months later is it fixed? I can of course test your fix if you 
couldn't. Let me know!

**Comment by IvanMalison** [comment]
I think I did SOME stuff to fix it, but ran in to an issue making in python2 and 3 compatible. I need to take a look at some other issues in the codebase this weekend so I can take a look at this again too.

**Comment by hista** [comment]
Thanks Ivan, please let me know when I can test your fix then.

**Comment by hista** [comment]
Hi Ivan

Could you solve it this weekend?

Best regards

**Comment by IvanMalison** [comment]
the problem is that i cant test from my home ip, which makes things pretty annoying right now (have to run everything on aws...
